# Generated by Django 5.0.2 on 2024-12-08 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chantier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ListeMateriaux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='BonCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('date', models.DateField()),
                ('chantier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bons_commande', to='chantier.chantier')),
            ],
        ),
        migrations.CreateModel(
            name='MateriauBonCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unite', models.CharField(choices=[('kg', 'Kilogramme'), ('tonne', 'Tonne'), ('m³', 'Mètre cube')], max_length=20)),
                ('bon_commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiaux', to='chantier.boncommande')),
                ('materiau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chantier.listemateriaux')),
            ],
        ),
    ]
