# Generated by Django 5.1.4 on 2025-01-02 19:22

import chantier.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chantier', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boncommande',
            name='chantier',
        ),
        migrations.RemoveField(
            model_name='listemateriaux',
            name='prix_unitaire',
        ),
        migrations.AddField(
            model_name='boncommande',
            name='type',
            field=models.CharField(choices=[('gros_oeuvre', 'Gros Œuvre'), ('finition', 'Finition')], default='gros_oeuvre', max_length=20),
        ),
        migrations.AddField(
            model_name='listemateriaux',
            name='type',
            field=models.CharField(choices=[('gros_oeuvre', 'Gros œuvre'), ('finition', 'Finition'), ('main_doeuvre', 'Main d’œuvre')], default='gros_oeuvre', max_length=20),
        ),
        migrations.AddField(
            model_name='listemateriaux',
            name='unite',
            field=models.CharField(default='unit', max_length=20),
        ),
        migrations.AddField(
            model_name='materiauboncommande',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AlterField(
            model_name='listemateriaux',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='materiauboncommande',
            name='materiau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chantier.listemateriaux'),
        ),
        migrations.AlterField(
            model_name='materiauboncommande',
            name='unite',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='PartieChantier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('gros_oeuvre', 'Gros œuvre'), ('finition', 'Finition')], max_length=20)),
                ('chantier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='chantier.chantier')),
            ],
        ),
        migrations.AddField(
            model_name='boncommande',
            name='partie',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, related_name='bons_commande', to='chantier.partiechantier'),
        ),
    ]
