# Generated by Django 5.1.4 on 2025-01-11 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chantier', '0003_remove_materiauboncommande_unite'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionMateriau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddConstraint(
            model_name='partiechantier',
            constraint=models.UniqueConstraint(fields=('chantier', 'type'), name='unique_partie_per_type'),
        ),
        migrations.AddField(
            model_name='optionmateriau',
            name='materiau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='chantier.listemateriaux'),
        ),
    ]
