# Generated by Django 5.1.4 on 2025-01-11 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chantier', '0004_optionmateriau_partiechantier_unique_partie_per_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiauboncommande',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiau_bon_commandes', to='chantier.optionmateriau'),
        ),
    ]
