# Generated by Django 5.1.4 on 2025-01-11 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chantier', '0006_listemateriaux_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listemateriaux',
            name='unite',
        ),
    ]
