# Generated by Django 5.1.4 on 2025-01-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chantier', '0007_remove_listemateriaux_unite'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='optionmateriau',
            constraint=models.UniqueConstraint(fields=('materiau', 'valeur'), name='unique_materiau_valeur'),
        ),
    ]
