# Generated by Django 5.1.4 on 2025-01-13 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chantier', '0008_optionmateriau_unique_materiau_valeur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_paiement', models.CharField(choices=[('espece', 'Espèces'), ('cheque', 'Chèque')], max_length=10)),
                ('date_paiement', models.DateField(auto_now_add=True)),
                ('numero_cheque', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro de chèque')),
                ('nom_banque', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom de la banque')),
            ],
        ),
        migrations.AddField(
            model_name='boncommande',
            name='paiement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bon_commande', to='chantier.paiement'),
        ),
    ]
