# Generated by Django 5.1.4 on 2025-01-15 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chantier', '0010_remove_optionmateriau_unique_materiau_valeur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionmateriau',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='optionmateriau',
            name='type',
            field=models.CharField(choices=[('gros_oeuvre', 'Gros œuvre'), ('finition', 'Finition'), ('main_doeuvre', 'Main d’œuvre')], max_length=20),
        ),
    ]
