# Generated by Django 5.1.4 on 2025-01-15 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chantier', '0011_optionmateriau_name_alter_optionmateriau_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionmateriau',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
