# Generated by Django 5.1.4 on 2025-01-17 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chantier', '0012_alter_optionmateriau_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boncommande',
            name='paiement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bons_commande', to='chantier.paiement'),
        ),
    ]
