# Generated by Django 5.1.4 on 2025-01-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chantier', '0013_alter_boncommande_paiement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boncommande',
            name='reference',
            field=models.CharField(error_messages={'unique': 'Un bon de commande avec cette référence existe déjà.'}, max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='boncommande',
            unique_together={('reference', 'partie')},
        ),
    ]
