# Generated by Django 5.2.4 on 2026-05-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chantier', '0014_alter_boncommande_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boncommande',
            name='date_livraison',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boncommande',
            name='fournisseur',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='boncommande',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boncommande',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('commande', 'Commandé'), ('livre', 'Livré'), ('annule', 'Annulé')], default='en_attente', max_length=20),
        ),
        migrations.AddField(
            model_name='chantier',
            name='adresse',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='chantier',
            name='budget_previsionnel',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='chantier',
            name='client',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='chantier',
            name='date_debut',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chantier',
            name='date_fin_prevue',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chantier',
            name='statut',
            field=models.CharField(choices=[('planifie', 'Planifié'), ('en_cours', 'En cours'), ('pause', 'En pause'), ('termine', 'Terminé')], default='en_cours', max_length=20),
        ),
    ]
